#include "Cercle.h"




double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B5C begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B5C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B5F begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
