#include "Ex1.h"




int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B1F begin
{
    return 0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B1F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B21 begin
{
    return 0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B21 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B23 begin
{
    
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B23 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B26 begin
{
    
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B26 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherRsultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B29 begin
{
    
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B29 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
