#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B33 begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B33 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B37 begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B3B begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B3B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B3D begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B3D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
