#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B42 begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B46 begin
{
    return 0.0;
}
// section 10--28--98-79-5944251b:1931a7a9ec8:-8000:0000000000000B46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
