#include "voiture.h"




voiture::rouler(bool return, int pédalAccelérateur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E31 begin
{
}
// section -84-20-10-2--3702a9c9:1931a7a18ce:-8000:0000000000000E31 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
