#include "Cercle.h"




double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A44 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A47 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
