#include "Cercle.h"




double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A6A begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A6A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A6D begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A6D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
