#include "Class Ex1.h"




void Class Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A15 begin
{
    
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A15 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Class Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A17 begin
{
    return 0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A17 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Class Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A19 begin
{
    
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A19 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Class Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A1C begin
{
    return 0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A1C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Class Ex1::AfficherResultats(int CodeFrome)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A1F begin
{
    
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A1F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
