#include "Ex1.h"




int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A18 begin
{
    return 0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A18 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A1A begin
{
    return 0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A1A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A1C begin
{
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A1C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A1F begin
{
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A1F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A25 begin
{
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A25 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
