#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A41 begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A41 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A45 begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A4C begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A4C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A4F begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
