#include "FormesGeométriques.h"




double FormesGeométriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A28 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A28 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeométriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A2C begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A2C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeométriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A30 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeométriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A32 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A32 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
