#include "Rectangle.h"




double Rectangle::CalculerSurface(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A60 begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A64 begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
