#include "Rectangle.h"




double Rectangle::CalculerSurface(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A3C begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPermietre(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A3F begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A3F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
