#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A56 begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A56 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A5A begin
{
    return 0.0;
}
// section 10--28--98-86--3ce19404:1931a986c01:-8000:0000000000000A5A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
