#include "TriangleRectangle.h"




double TriangleRectangle::CalclerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A34 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A34 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A38 begin
{
    return 0.0;
}
// section 10--28--98-88--2922cc5c:1931a9d9678:-8000:0000000000000A38 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
