#include " Ex1.h"
#include "iostream"     // Meme fonctionlité que stdio.h (lecture clavier, console, etc...)



void  Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C45 begin
{
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int  Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C47 begin
{
    return 0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void  Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C4B begin
{
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int  Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C4E begin
{
    return 0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C4E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void  Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C70 begin
{
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C70 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
