#include "Cercle.h"




double Cercle::CalculerSurface(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C67 begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C67 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C6A begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C6A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
