#include "FormesGeometriques.h"




double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:000000000000086D begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:000000000000086D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:000000000000086F begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:000000000000086F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C37 begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C3B begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C3B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
