#include "Rectangle.h"




double Rectangle::CalculerSurface(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C5F begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C63 begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C63 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
