#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C54 begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C58 begin
{
    return 0.0;
}
// section 10--79-86-64--407fbba4:18bf116c057:-8000:0000000000000C58 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
